# CTRL + ALT + R to execute a request (extension: humao.rest-client)

### Create User
POST http://localhost:3333/users
Content-Type: application/json

{
  "name": "jack jack",
  "email": "jack.jack@example.com",
  "password": "123456"
}
