# CTRL + ALT + R to execute a request (extension: humao.rest-client)

### Variables
@apiurl = http://localhost:3333
@name = "admin1"
@email = "jack.jack@example.com"
@password = "123456"

### Create User
# @name create-user
POST {{apiurl}}/users HTTP/1.1
Content-Type: application/json

{
  "name": {{name}},
  "email": {{email}},
  "password": {{password}}
}

### Authenticate User
# @name authenticate
POST {{apiurl}}/sessions HTTP/1.1
Content-Type: application/json

{
  "email": {{email}},
  "password": {{password}}
}


### Profile
@token = {{authenticate.response.body.$.token}}
# @name profile
GET {{apiurl}}/me HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json


### Refresh Token
@cookies = {{authenticate.response.headers.Set-Cookie}}
# @name refresh-token
PATCH  {{apiurl}}/token/refresh HTTP/1.1
Cookie: {{cookies}}


### Create Gym
@cookies = {{authenticate.response.headers.Set-Cookie}}
# @name create-gym
POST {{apiurl}}/gyms HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "GO Gym",
  "description": "Some description",
  "phone": "11999999999",
  "latitude": -27.2092052,
  "longitude": -49.6401091
}
